import{S as b,i as c,a as w}from"./assets/vendor-BDPjZNE_.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const S="54968565-2cd96adb4d5f069c81d213fb9",v=document.querySelector("#search-form"),h=document.querySelector(".gallery"),s=document.querySelector(".load-more"),l=document.querySelector(".loader");let f="",d=1,u=0;const g=40,q=new b(".gallery a");v.addEventListener("submit",M);s.addEventListener("click",P);async function M(e){if(e.preventDefault(),f=e.currentTarget.elements.searchQuery.value.trim(),f===""){c.warning({title:"Warning",message:"Please enter a search term!"});return}d=1,h.innerHTML="",m(),await p()}async function P(){d+=1,m(),await p(),E()}async function p(){H();try{const e=await $(f,d);if(u=e.totalHits,e.hits.length===0){c.error({message:"Sorry, there are no images matching your search query."});return}O(e.hits),B()}catch(e){c.error({message:"Sorry, there was an error fetching the images."}),console.error("Error info:",e)}finally{x()}}async function $(e,o){return(await w.get("https://pixabay.com/api/",{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:g}})).data}function O(e){const o=e.map(({webformatURL:a,largeImageURL:i,tags:t,likes:r,views:n,comments:y,downloads:L})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${i}">
                <img class="gallery-image" src="${a}" alt="${t}" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes</b>${r}</p>
                <p class="info-item"><b>Views</b>${n}</p>
                <p class="info-item"><b>Comments</b>${y}</p>
                <p class="info-item"><b>Downloads</b>${L}</p>
            </div>
        </li>`).join("");h.insertAdjacentHTML("beforeend",o),q.refresh()}function B(){d*g>=u?(m(),u>0&&c.info({message:"We're sorry, but you've reached the end of search results."})):A()}function E(){const e=document.querySelector(".gallery-item");if(e){const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}function H(){l&&l.classList.remove("hidden")}function x(){l&&l.classList.add("hidden")}function A(){s&&s.classList.remove("hidden")}function m(){s&&s.classList.add("hidden")}
//# sourceMappingURL=index.js.map
